import { useEffect, useState } from 'react'
import { Trash2, Pencil, Plus } from 'lucide-react'
import { listCastings, saveCasting, removeCasting, listActivities, saveActivity, removeActivity, type Casting, type ModelActivity } from '../../shared/services/operationsService'
import { searchModels } from '../../shared/services/modelsService'
import { useToast } from '../../shared/components/Toast'

export function CastingsPage() {
  const [items, setItems] = useState<Casting[]>([]); const [edit, setEdit] = useState<Partial<Casting> | null>(null); const { showToast } = useToast()
  const load = () => listCastings().then(setItems).catch(() => showToast('error', 'Impossible de charger les castings'))
  useEffect(() => { void load() }, [])
  async function save(e: React.FormEvent) { e.preventDefault(); try { await saveCasting(edit!); setEdit(null); load(); showToast('success', 'Casting enregistré') } catch { showToast('error', 'Erreur lors de la sauvegarde') } }
  return <div className="space-y-6"><Header title="Castings" text="Créez et publiez les opportunités visibles par les mannequins." onAdd={() => setEdit({ name: '', client: '', event_date: '', type: '' })}/>{edit && <form onSubmit={save} className="grid gap-3 rounded-2xl border border-yms-100 bg-yms-50 p-5 sm:grid-cols-2"><Input label="Nom" value={edit.name ?? ''} onChange={v => setEdit({ ...edit, name: v })}/><Input label="Client" value={edit.client ?? ''} onChange={v => setEdit({ ...edit, client: v })}/><Input label="Date" type="date" value={edit.event_date ?? ''} onChange={v => setEdit({ ...edit, event_date: v })}/><Input label="Type" value={edit.type ?? ''} onChange={v => setEdit({ ...edit, type: v })}/><Actions onCancel={() => setEdit(null)}/></form>}<List>{items.map(x => <Item key={x.id} title={x.name} detail={`${x.type || 'Casting'} · ${x.client || 'YMS'} · ${x.event_date || 'Date à confirmer'}`} onEdit={() => setEdit(x)} onDelete={async () => { if (confirm('Supprimer ce casting ?')) { await removeCasting(x.id); load() } }}/>)}</List></div>
}

export function ActivitiesPage() {
  const [items, setItems] = useState<any[]>([]); const [models, setModels] = useState<any[]>([]); const [edit, setEdit] = useState<Partial<ModelActivity> | null>(null); const { showToast } = useToast()
  const load = () => listActivities().then(setItems).catch(() => showToast('error', 'Impossible de charger les activités'))
  useEffect(() => { load(); searchModels({ page: 1, pageSize: 1000 }).then(r => setModels(r.data)) }, [])
  async function save(e: React.FormEvent) { e.preventDefault(); try { await saveActivity(edit!); setEdit(null); load(); showToast('success', 'Activité enregistrée') } catch { showToast('error', 'Erreur lors de la sauvegarde') } }
  return <div className="space-y-6"><Header title="Activités" text="Ajoutez les activités qui seront visibles sur le profil du mannequin." onAdd={() => setEdit({ model_id: '', activity_type: '', description: '' })}/>{edit && <form onSubmit={save} className="grid gap-3 rounded-2xl border border-yms-100 bg-yms-50 p-5"><select required value={edit.model_id ?? ''} onChange={e => setEdit({ ...edit, model_id: e.target.value })} className="rounded-lg border p-3"><option value="">Choisir un mannequin</option>{models.map(m => <option key={m.id} value={m.id}>{m.first_name} {m.last_name} — {m.yms_id}</option>)}</select><Input label="Type d'activité" value={edit.activity_type ?? ''} onChange={v => setEdit({ ...edit, activity_type: v })}/><textarea value={edit.description ?? ''} onChange={e => setEdit({ ...edit, description: e.target.value })} placeholder="Description" className="rounded-lg border p-3"/><Actions onCancel={() => setEdit(null)}/></form>}<List>{items.map(x => <Item key={x.id} title={`${x.activity_type} — ${x.models?.first_name} ${x.models?.last_name}`} detail={x.description || 'Sans description'} onEdit={() => setEdit(x)} onDelete={async () => { if (confirm('Supprimer cette activité ?')) { await removeActivity(x.id); load() } }}/>)}</List></div>
}
function Header({ title, text, onAdd }: { title: string; text: string; onAdd: () => void }) { return <div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-bold text-gray-900">{title}</h1><p className="text-sm text-gray-500">{text}</p></div><button onClick={onAdd} className="flex items-center gap-2 rounded-lg bg-yms-600 px-4 py-2 text-sm font-semibold text-white"><Plus size={16}/>Ajouter</button></div> }
function Input({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (v: string) => void; type?: string }) { return <label className="text-sm font-medium text-gray-700">{label}<input required type={type} value={value} onChange={e => onChange(e.target.value)} className="mt-1 block w-full rounded-lg border p-3"/></label> }
function Actions({ onCancel }: { onCancel: () => void }) { return <div className="flex gap-2"><button className="rounded-lg bg-yms-600 px-4 py-2 text-sm font-semibold text-white">Enregistrer</button><button type="button" onClick={onCancel} className="rounded-lg border px-4 py-2 text-sm">Annuler</button></div> }
function List({ children }: { children: React.ReactNode }) { return <div className="divide-y overflow-hidden rounded-2xl border bg-white">{children}</div> }
function Item({ title, detail, onEdit, onDelete }: { title: string; detail: string; onEdit: () => void; onDelete: () => void }) { return <div className="flex items-center justify-between gap-3 p-4"><div><p className="font-semibold">{title}</p><p className="text-sm text-gray-500">{detail}</p></div><div className="flex gap-2"><button onClick={onEdit} className="rounded p-2 text-yms-700 hover:bg-yms-50"><Pencil size={17}/></button><button onClick={onDelete} className="rounded p-2 text-red-600 hover:bg-red-50"><Trash2 size={17}/></button></div></div> }
